-- RETRIVE CUSTOMERS WITH A SCORE NOT EQUAL TO 0 --
USE MyDatabase;
SELECT * 
FROM customers
WHERE score != 0

-- RETRIVE CUSTOMERS WITH A SCORE NOT EQUAL TO GERMANY --
SELECT * 
FROM customers
WHERE country = 'Germany'

-- ORDER BY --

/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY 
THE HIGHEST SCORE FIRST. */

SELECT * 
FROM customers
ORDER BY score DESC

/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY 
THE LOWEST SCORE FIRST. */

SELECT * 
FROM customers
ORDER BY score ASC

/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY THE 
COUNTRY AND THEN BY THE HIGHEST SCORE */

SELECT * 
FROM customers
ORDER BY country ASC, score DESC

-- GROUP BY --
/* FIND THE TOTAL SCORE BY COUNTRY */

SELECT 
    country,
    first_name,
    SUM(score) AS TOTAL_SCORE 
FROM customers
GROUP BY country, first_name

/* FIND THE TOTAL SCORE AND TOTAL NUMBER OF CUSTOMERS
FOR EACH COUNTRY */

SELECT 
country,
SUM(score) AS TOTAL_SCORE,
COUNT(id)  AS TOTAL_CUSTOMERS
FROM customers
GROUP BY country

-- HAVING AGGREGATION --

SELECT
country,
SUM(score) AS TOTAL_SCORE
FROM customers
WHERE score > 400
GROUP BY country
HAVING SUM(score) > 800

/* FIND THE AVERAGE SCORE FOR EACH COUNTRY
CONSIDERING ONLY CUSTOMERS WITH A SCORE NOT EQUAL TO 0 AND RETURN 
ONLY THOSE COUNTRIES WITH AN AVERAGE SCORE GREAT THAN 430 */

SELECT
    country,
    AVG(score) AS AVG_SCORE
FROM customers
WHERE score != 0
GROUP BY country
HAVING AVG(score) > 430

-- DISTINCT --

/* RETURN UNIQUE LIST OF ALL COUNTRIES */

SELECT DISTINCT country
FROM customers

-- TOP --
/* RETRIEVE ONLY 3 CUSTOMERS */

SELECT TOP 3 * 
FROM customers

/* RETRIEVE THE TOP 3 CUSTOMERS WITH THE HIGHEST SCORE */

SELECT TOP 3 * 
FROM customers
ORDER BY score DESC

/* RETRIEVE THE LOWEST 2 CUSTOMERS BASED ON THE SCORE */

SELECT TOP 2 * 
FROM customers
ORDER BY score ASC

/* GET THE TWO MOST RECENT ORDERS */

SELECT TOP 2 * 
FROM orders
ORDER BY order_date DESC




