-- RETRIVE CUSTOMERS WITH A SCORE NOT EQUAL TO 0 --
USE MyDatabase;
SELECT * 
FROM customers
WHERE score != 0

-- RETRIVE CUSTOMERS WITH A SCORE NOT EQUAL TO GERMANY --
USE MyDatabase;
SELECT * 
FROM customers
WHERE country = 'Germany'

/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY 
THE HIGHEST SCIORE FIRST. */

SELECT * 
FROM customers

/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY 
THE LOWEST SCORE FIRST. */
SELECT * 
FROM customers
ORDER BY score ASC

/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY THE 
COUNTRY AND THEN BY THE HIGHEST SCORE */

SELECT * 
FROM customers
ORDER BY country ASC, score DESC

-- GROUP BY --
/* FIND THE TOTAL SCORE BY COUNTRY */

SELECT 
    country,
    first_name,
    SUM(score) AS TOTAL_SCORE 
FROM customers
GROUP BY country, first_name

/* FIND THE TOTAL SCORE AND TOTAL NUMBER OF CUSTOMERS
FOR EACH COUNTRY */

SELECT 
country,
SUM(score) AS TOTAL_SCORE,
COUNT(id)  AS TOTAL_CUSTOMERS
FROM customers
GROUP BY country

-- HAVING AGGREGATION --

SELECT
country,
SUM(score) AS TOTAL_SCORE
FROM customers
WHERE score > 400
GROUP BY country
HAVING SUM(score) > 800

/* FIND THE AVERAGE SCORE FOR EACH COUNTRY
CONSIDERING ONLY CUSTOMERS WITH A SCORE NOT EQUAL TO 0 AND RETURN 
ONLY THOSE COUNTRIES WITH AN AVERAGE SCORE GREAT THAN 430 */

SELECT
    country,
    AVG(score) AS AVG_SCORE
FROM customers
WHERE score != 0
GROUP BY country
HAVING AVG(score) > 430

-- DISTINCT --

/* RETURN UNIQUE LIST OF ALL COUNTRIES */

SELECT DISTINCT country
FROM customers

-- TOP --
/* RETRIEVE ONLY 3 CUSTOMERS */

SELECT * FROM Customers
LIMIT 3;

/* RETRIEVE THE TOP 3 CUSTOMERS WITH THE HIGHEST SCORE */

SELECT  * 
FROM customers
ORDER BY score DESC
LIMIT 3;

/* RETRIEVE THE LOWEST 2 CUSTOMERS BASED ON THE SCORE */

SELECT * 
FROM customers
ORDER BY score ASC
LIMIT 2;

/* GET THE TWO MOST RECENT ORDERS */

SELECT * 
FROM orders
ORDER BY order_date DESC
LIMIT 2;

-- MULTI QUERIES --

USE MyDatabase;
SELECT * 
FROM customers;

SELECT * 
FROM orders;

-- STATIC QUERY --

SELECT 123 AS STATIC_NUMBER 

SELECT 'HELLO' AS `STATIC DATA`;


SELECT 
    id,
    first_name,
'NEW_CUSTOMER' AS CUSTOMER_TYPE
FROM customers

-- COOL SQL TECHNIQUES --
/* HIGHLIGHT AND EXCUTE */

SELECT *
FROM customers
WHERE country = 'Germany';

SELECT * FROM orders;








