-- RETRIVE CUSTOMERS WITH A SCORE NOT EQUAL TO 0 --
USE MyDatabase;
SELECT * 
FROM customers
WHERE score != 0

-- RETRIVE CUSTOMERS WITH A SCORE NOT EQUAL TO GERMANY --
USE MyDatabase;
SELECT * 
FROM customers
WHERE country = 'Germany'

/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY 
THE HIGHEST SCIORE FIRST. */

SELECT * 
FROM customers

/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY 
THE LOWEST SCORE FIRST. */
SELECT * 
FROM customers
ORDER BY score ASC

/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY THE 
COUNTRY AND THEN BY THE HIGHEST SCORE */

SELECT * 
FROM customers
ORDER BY country ASC, score DESC

-- GROUP BY --
/* FIND THE TOTAL SCORE BY COUNTRY */

SELECT 
    country,
    first_name,
    SUM(score) AS TOTAL_SCORE 
FROM customers
GROUP BY country, first_name

/* FIND THE TOTAL SCORE AND TOTAL NUMBER OF CUSTOMERS
FOR EACH COUNTRY */

SELECT 
country,
SUM(score) AS TOTAL_SCORE,
COUNT(id)  AS TOTAL_CUSTOMERS
FROM customers
GROUP BY country

-- HAVING AGGREGATION --

SELECT
country,
SUM(score) AS TOTAL_SCORE
FROM customers
WHERE score > 400
GROUP BY country
HAVING SUM(score) > 800

/* FIND THE AVERAGE SCORE FOR EACH COUNTRY
CONSIDERING ONLY CUSTOMERS WITH A SCORE NOT EQUAL TO 0 AND RETURN 
ONLY THOSE COUNTRIES WITH AN AVERAGE SCORE GREAT THAN 430 */

SELECT
    country,
    AVG(score) AS AVG_SCORE
FROM customers
WHERE score != 0
GROUP BY country
HAVING AVG(score) > 430