-- RETRIVE CUSTOMERS WITH A SCORE NOT EQUAL TO 0 --
USE MyDatabase;
SELECT * 
FROM customers
WHERE score != 0

-- RETRIVE CUSTOMERS WITH A SCORE NOT EQUAL TO GERMANY --
USE MyDatabase;
SELECT * 
FROM customers
WHERE country = 'Germany'

/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY 
THE HIGHEST SCIORE FIRST. */

SELECT * 
FROM customers

/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY 
THE LOWEST SCORE FIRST. */
SELECT * 
FROM customers
ORDER BY score ASC

/* RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY THE 
COUNTRY AND THEN BY THE HIGHEST SCORE */

SELECT * 
FROM customers
ORDER BY country ASC, score DESC